### ISSUE TITLE
The query is missing in the doc

### ISSUE THREAD

**Issue by gmarchand** [awslabs/aws-streaming-media-analytics#5]
https://github.com/awslabs/aws-streaming-media-analytics/blame/master/workshop/LAB3.md#L115

"To query the total views of the video named oceans, enter the following query into the Queries console and click the Play button to execute the query:"

The following query does not exist

**Comment by alcousins** [comment]
Ah! the .md is a partial extract from a lab guide. I'll get this updated in the next few days. In the short-term, here is the current, up-to-date version of the lab guide:

https://aws-streaming-media-analytics-workshop.s3.amazonaws.com/index.html

**Comment by gmarchand** [comment]
Thanks
