### ISSUE TITLE
Customers would want a new UX for this workshop

### ISSUE THREAD

**Issue by gmarchand** [awslabs/aws-streaming-media-analytics#6]
Customers told me is difficult to follow this workshop with a laptop, because there is a lot of text and they need to scroll a lot to find the information.

I have showed them this theme used by eksworkshop.com. 
https://learn.netlify.com/en/
All told me it will be easier to follow this workshop with this theme and "Automatic next/prev buttons to navigate through menu entries"

**Comment by alcousins** [comment]
Please follow the guide used at public workshops: https://aws-streaming-media-analytics-workshop.s3.amazonaws.com/index.html . We put a lot of work into making this easy to follow. 

I'll get the .md files in this repo updated shortly, they are out of sync with the website. Our bad for this gap, but the website isn't generated from the md files so reconciling is non-trivial.

**Comment by gmarchand** [comment]
Thank you for the info.
